### ISSUE TITLE
Opacity 0.5 for the inactive Stopify logo

### ISSUE THREAD

**Issue by ivanovd** [skuethe/MMM-Spotify#24]
How can I make the opacity of the Spotify logo (when there is no music playing) 0.5? It is too obtrusive and distracting at 100% opacity.

**Comment by eouia** [comment]
Sorry for late reply. I was on vacation.
You can change `/resources/spotify-xxl.png` with your owns.
Or, 
```css
.noPlayback #SPOTIFY_COVER_IMAGE {
  opacity:0.5;
}
```
might work. (I couldn't test at this moment)
